services:
  front:
    build: ./
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    ports:
      - 5173:5173
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./front:/front
      - node_modules:/front/node_modules

#   web:
#     image: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - front
#     restart: always

volumes:
  node_modules: