services:
  front:
    build: ./
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    ports:
      - 3000:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./front:/front

#   web:
#     image: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - front
#     restart: always